# Generated by Django 5.0.14 on 2026-02-13 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0002_cliente_pedidos"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Pedidos",
            new_name="Pedido",
        ),
    ]
